(function (root, factory) {
  "use strict";

  const entries = factory();

  if (typeof module !== "undefined" && module.exports) {
    module.exports = entries;
  }

  if (root) {
    root.CatalogueSeeds = root.CatalogueSeeds || {};
    const existing = Array.isArray(root.CatalogueSeeds.feature) ? root.CatalogueSeeds.feature : [];
    const ids = new Set(existing.map((entry) => entry?.id).filter(Boolean));
    root.CatalogueSeeds.feature = existing.concat(entries.filter((entry) => !ids.has(entry.id)));
  }
})(typeof window !== "undefined" ? window : null, function () {
  "use strict";

  return [
    {
      id: "feature-rage",
      linkId: "rage",
      name: "Rage",
      featureType: "Class feature",
      grantedBy: "@class:class-barbarian|Barbarian",
      levelPrerequisite: "1",
      source: "Core rules",
      page: "",
      summary: "Enter a battle fury that improves melee pressure and makes ordinary weapon damage easier to endure.",
      description: "Rage is the barbarian's central combat state. While raging, the character gains the class's listed offensive and defensive benefits, but must respect the feature's restrictions and duration rules. Uses, damage bonus, and later improvements scale with barbarian level.",
      usesRecharge: "Limited uses / long rest",
      notes: "Exact benefits differ between 2014 and 2024 rules. Use the campaign ruleset when checking damage, resistance, duration, and activation details.",
      tags: ["class", "barbarian", "combat", "core"]
    },
    {
      id: "feature-reckless-attack",
      linkId: "reckless-attack",
      name: "Reckless Attack",
      featureType: "Class feature",
      grantedBy: "@class:class-barbarian|Barbarian",
      levelPrerequisite: "2",
      source: "Core rules",
      page: "",
      summary: "Trade safety for accuracy by attacking recklessly and leaving yourself easier to hit in return.",
      description: "Reckless Attack lets a barbarian deliberately open their defense to improve qualifying attacks on their turn. The same commitment gives enemies an easier time striking back until the feature's stated timing ends.",
      usesRecharge: "At will",
      notes: "A clean risk-versus-reward button. Check the active ruleset for which attacks qualify and exactly how long the drawback lasts.",
      tags: ["class", "barbarian", "combat", "advantage"]
    },
    {
      id: "feature-bardic-inspiration",
      linkId: "bardic-inspiration",
      name: "Bardic Inspiration",
      featureType: "Class feature",
      grantedBy: "@class:class-bard|Bard",
      levelPrerequisite: "1",
      source: "Core rules",
      page: "",
      summary: "Give an ally a Bardic Inspiration die that can improve an important roll.",
      description: "Bardic Inspiration turns the bard's encouragement, performance, or supernatural confidence into a limited-use die for another creature. The die size, valid rolls, timing, and recharge improve as the bard advances.",
      usesRecharge: "Limited uses; recharge depends on level/ruleset",
      notes: "Keep the inspiration die visible on the recipient's sheet until spent or expired.",
      tags: ["class", "bard", "support", "inspiration"]
    },
    {
      id: "feature-channel-divinity",
      linkId: "channel-divinity",
      name: "Channel Divinity",
      featureType: "Class feature",
      grantedBy: "Cleric / Paladin",
      levelPrerequisite: "Varies",
      source: "Core rules",
      page: "",
      summary: "Spend a divine resource on powerful class or subclass effects.",
      description: "Channel Divinity is a shared resource framework used by divine classes. The available effects come from the class and subclass, while the number of uses and recharge cadence depend on level and ruleset.",
      usesRecharge: "Limited uses; class/ruleset dependent",
      notes: "Treat individual Channel Divinity options as children of this resource rather than separate resource pools unless a rule says otherwise.",
      tags: ["class", "cleric", "paladin", "divine", "resource"]
    },
    {
      id: "feature-lay-on-hands",
      linkId: "lay-on-hands",
      name: "Lay on Hands",
      featureType: "Class feature",
      grantedBy: "@class:class-paladin|Paladin",
      levelPrerequisite: "1",
      source: "Core rules",
      page: "",
      summary: "Draw from a healing pool to restore allies or handle certain harmful conditions.",
      description: "Lay on Hands gives a paladin a daily pool of restorative power. The paladin can spend some or all of that pool on eligible creatures, with additional uses depending on the campaign's ruleset.",
      usesRecharge: "Healing pool / long rest",
      notes: "Track the pool as a number, not as spell slots. Its size scales with paladin level.",
      tags: ["class", "paladin", "healing", "divine"]
    },
    {
      id: "feature-cunning-action",
      linkId: "cunning-action",
      name: "Cunning Action",
      featureType: "Class feature",
      grantedBy: "@class:class-rogue|Rogue",
      levelPrerequisite: "2",
      source: "Core rules",
      page: "",
      summary: "Use a bonus action for signature rogue mobility and positioning options.",
      description: "Cunning Action compresses useful movement and positioning choices into the rogue's bonus action. The exact menu depends on ruleset, but it is the feature that makes rogues unusually slippery from turn to turn.",
      usesRecharge: "At will",
      notes: "A rogue often wants their bonus action free, so remember the opportunity cost when another feature competes for it.",
      tags: ["class", "rogue", "movement", "bonus-action"]
    },
    {
      id: "feature-uncanny-dodge",
      linkId: "uncanny-dodge",
      name: "Uncanny Dodge",
      featureType: "Class feature",
      grantedBy: "@class:class-rogue|Rogue",
      levelPrerequisite: "5",
      source: "Core rules",
      page: "",
      summary: "Use your reaction to sharply reduce damage from a qualifying attack that hits you.",
      description: "Uncanny Dodge lets a rogue turn a reaction into immediate damage mitigation when the feature's trigger is met. It is powerful, but spending the reaction means it cannot be used again before the rogue regains it.",
      usesRecharge: "Reaction",
      notes: "It reduces damage from its qualifying hit rather than making the attack miss.",
      tags: ["class", "rogue", "defense", "reaction"]
    },
    {
      id: "feature-metamagic",
      linkId: "metamagic",
      name: "Metamagic",
      featureType: "Class feature",
      grantedBy: "@class:class-sorcerer|Sorcerer",
      levelPrerequisite: "Varies by ruleset",
      source: "Core rules",
      page: "",
      summary: "Spend sorcerous resources to alter how a spell behaves when you cast it.",
      description: "Metamagic gives sorcerers a menu of ways to reshape spells, such as changing reach, targets, timing, or other casting properties. Known options and resource costs depend on the chosen option and ruleset.",
      usesRecharge: "Sorcery points",
      notes: "Record each chosen Metamagic option separately in character notes if quick table access matters.",
      tags: ["class", "sorcerer", "magic", "spellcasting", "resource"]
    },
    {
      id: "feature-pact-magic",
      linkId: "pact-magic",
      name: "Pact Magic",
      featureType: "Class feature",
      grantedBy: "@class:class-warlock|Warlock",
      levelPrerequisite: "1",
      source: "Core rules",
      page: "",
      summary: "Warlock spellcasting built around a small pool of unusually renewable spell slots.",
      description: "Pact Magic uses a progression distinct from ordinary full-caster spell slots. Warlocks have relatively few slots, cast them according to the class's slot level rules, and recover them on the cadence specified by the active ruleset.",
      usesRecharge: "Pact slots; rest cadence depends on ruleset",
      notes: "Keep Pact Magic slots separate from ordinary Spellcasting slots on multiclass characters.",
      tags: ["class", "warlock", "magic", "spellcasting"]
    },
    {
      id: "feature-eldritch-invocations",
      linkId: "eldritch-invocations",
      name: "Eldritch Invocations",
      featureType: "Class feature",
      grantedBy: "@class:class-warlock|Warlock",
      levelPrerequisite: "Varies by ruleset",
      source: "Core rules",
      page: "",
      summary: "Choose modular supernatural upgrades that customize a warlock's magic and utility.",
      description: "Eldritch Invocations are selectable warlock features with their own prerequisites and effects. They can enhance spells, grant persistent abilities, unlock new magic, or reshape how the class plays.",
      usesRecharge: "Varies by invocation",
      notes: "Individual invocations are good candidates for their own Feature entries once a campaign actually uses them.",
      tags: ["class", "warlock", "magic", "customization"]
    },
    {
      id: "feature-fighting-style",
      linkId: "fighting-style",
      name: "Fighting Style",
      featureType: "Class feature",
      grantedBy: "Fighter / Paladin / Ranger and other sources",
      levelPrerequisite: "Varies",
      source: "Core rules",
      page: "",
      summary: "Choose a focused martial specialty that improves a recurring combat approach.",
      description: "Fighting Style is a family of selectable martial bonuses. The available styles and their exact effects depend on class, level, source, and ruleset.",
      usesRecharge: "Passive",
      notes: "Store the chosen style by name on the character rather than treating this parent entry as the final mechanical effect.",
      tags: ["class", "martial", "combat", "choice"]
    },
    {
      id: "feature-extra-attack",
      linkId: "extra-attack",
      name: "Extra Attack",
      featureType: "Class feature",
      grantedBy: "Multiple martial classes",
      levelPrerequisite: "Usually 5",
      source: "Core rules",
      page: "",
      summary: "Make more than one attack when you take the Attack action.",
      description: "Extra Attack increases the number of attacks a character can make as part of a single Attack action. Most versions do not stack with each other; use the best number of attacks granted by the character's relevant features unless a rule explicitly says otherwise.",
      usesRecharge: "Passive",
      notes: "Fighter progression can improve this feature beyond two attacks.",
      tags: ["class", "martial", "combat", "attack"]
    },
    {
      id: "feature-dwarven-resilience",
      linkId: "dwarven-resilience",
      name: "Dwarven Resilience",
      featureType: "Species feature",
      grantedBy: "@race:race-dwarf|Dwarf",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Dwarven toughness makes poison easier to resist and less punishing when it gets through.",
      description: "Dwarven Resilience represents a dwarf's supernatural or physiological hardiness against poison. Apply the advantage and resistance specified by the version of the species used in the campaign.",
      usesRecharge: "Passive",
      notes: "A compact reminder feature for older core dwarf presentations.",
      tags: ["species", "dwarf", "poison", "defense"]
    },
    {
      id: "feature-halfling-lucky",
      linkId: "halfling-lucky",
      name: "Lucky (Halfling)",
      featureType: "Species feature",
      grantedBy: "@race:race-halfling|Halfling",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Halfling luck lets disastrous natural 1s on certain d20 rolls get another chance.",
      description: "This species feature improves reliability by allowing qualifying natural 1 results to be rerolled. It is distinct from the Lucky feat despite the shared name in older rules.",
      usesRecharge: "Passive",
      notes: "Kept under a disambiguated Compendium name so it cannot be confused with the feat.",
      tags: ["species", "halfling", "luck", "reroll"]
    },
    {
      id: "feature-brave",
      linkId: "brave",
      name: "Brave",
      featureType: "Species feature",
      grantedBy: "@race:race-halfling|Halfling",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Halflings are unusually resistant to fear.",
      description: "Brave improves a halfling's ability to resist the frightened condition according to the species rules being used.",
      usesRecharge: "Passive",
      notes: "",
      tags: ["species", "halfling", "fear", "defense"]
    },
    {
      id: "feature-halfling-nimbleness",
      linkId: "halfling-nimbleness",
      name: "Halfling Nimbleness",
      featureType: "Species feature",
      grantedBy: "@race:race-halfling|Halfling",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Slip through spaces occupied by creatures larger than you when the species rule allows it.",
      description: "Halfling Nimbleness makes the species unusually good at moving through crowded battlefields. Check the active ruleset for exactly which creature sizes and movement restrictions apply.",
      usesRecharge: "Passive",
      notes: "",
      tags: ["species", "halfling", "movement"]
    },
    {
      id: "feature-gnome-cunning",
      linkId: "gnome-cunning",
      name: "Gnome Cunning",
      featureType: "Species feature",
      grantedBy: "@race:race-gnome|Gnome",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Gnomish mental resilience improves resistance against particular magical effects.",
      description: "Gnome Cunning represents a gnome's practiced or innate resistance to hostile magic that targets the mind. The qualifying saving throws differ between rules presentations, so use the campaign's version.",
      usesRecharge: "Passive",
      notes: "",
      tags: ["species", "gnome", "magic", "defense"]
    },
    {
      id: "feature-breath-weapon",
      linkId: "breath-weapon",
      name: "Breath Weapon",
      featureType: "Species feature",
      grantedBy: "@race:race-dragonborn|Dragonborn",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Exhale draconic energy in an area using the damage type tied to your ancestry.",
      description: "A dragonborn's Breath Weapon creates an elemental area attack. Shape, damage, saving throw, scaling, uses, and action economy vary significantly across 5e rules presentations.",
      usesRecharge: "Limited uses; ruleset dependent",
      notes: "Record the chosen ancestry or damage type next to this feature for fast play.",
      tags: ["species", "dragonborn", "dragon", "area", "damage"]
    },
    {
      id: "feature-hellish-resistance",
      linkId: "hellish-resistance",
      name: "Hellish Resistance",
      featureType: "Species feature",
      grantedBy: "@race:race-tiefling|Tiefling",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Infernal heritage grants resistance to fire damage.",
      description: "Hellish Resistance is the classic tiefling defense against fire. If the campaign uses a newer tiefling presentation with lineage-specific changes, follow that version instead.",
      usesRecharge: "Passive",
      notes: "",
      tags: ["species", "tiefling", "fire", "resistance"]
    },
    {
      id: "feature-infernal-legacy",
      linkId: "infernal-legacy",
      name: "Infernal Legacy",
      featureType: "Species feature",
      grantedBy: "@race:race-tiefling|Tiefling",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Infernal ancestry unlocks a small progression of innate magic.",
      description: "Infernal Legacy is the older core framework for tiefling innate spellcasting. The exact cantrip, leveled spells, casting ability, and recharge change across tiefling versions and newer lineage options.",
      usesRecharge: "Innate magic; level/ruleset dependent",
      notes: "Keep this entry as a pointer when using the classic core tiefling rather than assuming every later tiefling uses the same spell package.",
      tags: ["species", "tiefling", "magic", "infernal"]
    },
    {
      id: "feature-relentless-endurance",
      linkId: "relentless-endurance",
      name: "Relentless Endurance",
      featureType: "Species feature",
      grantedBy: "@race:race-half-orc|Half-Orc",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Refuse to fall once when damage would otherwise drop you to 0 HP.",
      description: "Relentless Endurance gives the classic half-orc a limited ability to remain standing at 1 HP instead of dropping to 0 when the feature's trigger and exclusions are satisfied.",
      usesRecharge: "1 / long rest",
      notes: "",
      tags: ["species", "half-orc", "survival", "defense"]
    },
    {
      id: "feature-savage-attacks",
      linkId: "savage-attacks",
      name: "Savage Attacks",
      featureType: "Species feature",
      grantedBy: "@race:race-half-orc|Half-Orc",
      levelPrerequisite: "",
      source: "Core rules",
      page: "",
      summary: "Critical melee weapon hits gain an additional weapon damage die in the classic half-orc rules.",
      description: "Savage Attacks increases the payoff of qualifying critical hits. It is a species feature and is distinct from the Savage Attacker feat despite the similar name.",
      usesRecharge: "Passive",
      notes: "Keep the species feature and feat as separate Compendium entries.",
      tags: ["species", "half-orc", "critical", "damage"]
    }
  ];
});
