/**
 * Core skill catalogue seeds (5e-style starters).
 * Data only — not hardcoded in application logic. Custom skills welcome.
 */
window.CatalogueSeeds = window.CatalogueSeeds || {};

window.CatalogueSeeds.skill = [
  {
    id: "skill-acrobatics",
    linkId: "acrobatics",
    name: "Acrobatics",
    defaultAbility: "Dexterity",
    source: "Player's Handbook",
    page: "",
    summary: "Stay on your feet in tricky situations.",
    description: "Your Dexterity (Acrobatics) check covers your attempt to stay on your feet in a tricky situation, such as when you're trying to run across a sheet of ice, balance on a tightrope, or stay upright on a rocking ship's deck.",
    typicalUses: "Balance, tumble, stunts, keeping footing on unstable ground.",
    exampleChecks: "Walk a narrow ledge; land safely after a fall; tumble through an enemy's space.",
    notes: "",
    tags: ["dexterity", "movement"]
  },
  {
    id: "skill-animal-handling",
    linkId: "animal-handling",
    name: "Animal Handling",
    defaultAbility: "Wisdom",
    source: "Player's Handbook",
    page: "",
    summary: "Calm, control, or read an animal.",
    description: "When there is any question whether you can calm down a domesticated animal, keep a mount from getting spooked, or intuit an animal's intentions, the GM might call for a Wisdom (Animal Handling) check.",
    typicalUses: "Calm mounts, train beasts, read animal mood, guide beasts.",
    exampleChecks: "Quiet a frightened horse; coax a watchdog; sense if a beast is about to attack.",
    notes: "",
    tags: ["wisdom", "nature"]
  },
  {
    id: "skill-arcana",
    linkId: "arcana",
    name: "Arcana",
    defaultAbility: "Intelligence",
    source: "Player's Handbook",
    page: "",
    summary: "Knowledge of spells, magic items, and planar lore.",
    description: "Your Intelligence (Arcana) check measures your ability to recall lore about spells, magic items, eldritch symbols, magical traditions, the planes of existence, and the inhabitants of those planes.",
    typicalUses: "Identify magic traditions, planar signs, occult symbols.",
    exampleChecks: "Recognize a ritual circle; recall a magic item's school; identify an aberration's nature.",
    notes: "",
    tags: ["intelligence", "magic"]
  },
  {
    id: "skill-athletics",
    linkId: "athletics",
    name: "Athletics",
    defaultAbility: "Strength",
    source: "Player's Handbook",
    page: "",
    summary: "Climbing, jumping, and swimming.",
    description: "Your Strength (Athletics) check covers difficult situations you encounter while climbing, jumping, or swimming.",
    typicalUses: "Climb, jump, swim, grapple contests (often).",
    exampleChecks: "Scale a cliff; long jump a chasm; swim against a current.",
    notes: "",
    tags: ["strength", "movement"]
  },
  {
    id: "skill-deception",
    linkId: "deception",
    name: "Deception",
    defaultAbility: "Charisma",
    source: "Player's Handbook",
    page: "",
    summary: "Hide the truth convincingly.",
    description: "Your Charisma (Deception) check determines whether you can convincingly hide the truth, either verbally or through your actions.",
    typicalUses: "Lies, disguises, false intentions, con games.",
    exampleChecks: "Bluff a guard; pass as another person; feint in social play.",
    notes: "",
    tags: ["charisma", "social"]
  },
  {
    id: "skill-history",
    linkId: "history",
    name: "History",
    defaultAbility: "Intelligence",
    source: "Player's Handbook",
    page: "",
    summary: "Recall historical lore and legends.",
    description: "Your Intelligence (History) check measures your ability to recall lore about historical events, legendary people, ancient kingdoms, past disputes, recent wars, and lost civilizations.",
    typicalUses: "Royalty, wars, ruins, famous figures.",
    exampleChecks: "Identify a heraldic crest; date a ruin; recall a treaty.",
    notes: "",
    tags: ["intelligence", "knowledge"]
  },
  {
    id: "skill-insight",
    linkId: "insight",
    name: "Insight",
    defaultAbility: "Wisdom",
    source: "Player's Handbook",
    page: "",
    summary: "Read body language and motives.",
    description: "Your Wisdom (Insight) check decides whether you can determine the true intentions of a creature, such as when searching out a lie or predicting someone's next move.",
    typicalUses: "Detect lies, sense motives, read a room.",
    exampleChecks: "Spot a bluff; sense hostility behind polite words.",
    notes: "",
    tags: ["wisdom", "social"]
  },
  {
    id: "skill-intimidation",
    linkId: "intimidation",
    name: "Intimidation",
    defaultAbility: "Charisma",
    source: "Player's Handbook",
    page: "",
    summary: "Influence through threats or force of presence.",
    description: "When you attempt to influence someone through overt threats, hostile actions, and physical violence, the GM might ask you to make a Charisma (Intimidation) check.",
    typicalUses: "Threats, interrogation, scare tactics.",
    exampleChecks: "Cow a thug; force a confession; clear a tavern with a glare.",
    notes: "",
    tags: ["charisma", "social"]
  },
  {
    id: "skill-investigation",
    linkId: "investigation",
    name: "Investigation",
    defaultAbility: "Intelligence",
    source: "Player's Handbook",
    page: "",
    summary: "Deduce clues and search carefully.",
    description: "When you look around for clues and make deductions based on those clues, you make an Intelligence (Investigation) check.",
    typicalUses: "Search rooms, deduce crime scenes, find hidden objects by reasoning.",
    exampleChecks: "Find a secret door by studying walls; deduce which cup was poisoned.",
    notes: "",
    tags: ["intelligence", "exploration"]
  },
  {
    id: "skill-medicine",
    linkId: "medicine",
    name: "Medicine",
    defaultAbility: "Wisdom",
    source: "Player's Handbook",
    page: "",
    summary: "Stabilize and diagnose injuries.",
    description: "A Wisdom (Medicine) check lets you try to stabilize a dying companion or diagnose an illness.",
    typicalUses: "Stabilize, diagnose disease/poison, treat wounds.",
    exampleChecks: "Identify a poison; stabilize a fallen ally; judge cause of death.",
    notes: "",
    tags: ["wisdom", "healing"]
  },
  {
    id: "skill-nature",
    linkId: "nature",
    name: "Nature",
    defaultAbility: "Intelligence",
    source: "Player's Handbook",
    page: "",
    summary: "Knowledge of terrain, plants, animals, and weather.",
    description: "Your Intelligence (Nature) check measures your ability to recall lore about terrain, plants and animals, the weather, and natural cycles.",
    typicalUses: "Identify flora/fauna, weather patterns, natural hazards.",
    exampleChecks: "Recognize a rare herb; predict a storm; know why animals avoid a shore.",
    notes: "",
    tags: ["intelligence", "wilderness"]
  },
  {
    id: "skill-perception",
    linkId: "perception",
    name: "Perception",
    defaultAbility: "Wisdom",
    source: "Player's Handbook",
    page: "",
    summary: "Spot, hear, or otherwise detect presence.",
    description: "Your Wisdom (Perception) check lets you spot, hear, or otherwise detect the presence of something. It measures your general awareness of your surroundings and the keenness of your senses.",
    typicalUses: "Spot traps/hidden foes, listen at doors, notice ambushes.",
    exampleChecks: "Hear whispering; notice a camouflaged hunter; spot a tripwire.",
    notes: "",
    tags: ["wisdom", "senses"]
  },
  {
    id: "skill-performance",
    linkId: "performance",
    name: "Performance",
    defaultAbility: "Charisma",
    source: "Player's Handbook",
    page: "",
    summary: "Entertain an audience.",
    description: "Your Charisma (Performance) check determines how well you can delight an audience with music, dance, acting, storytelling, or some other form of entertainment.",
    typicalUses: "Music, dance, acting, oratory entertainment.",
    exampleChecks: "Win a crowd; distract with a song; impress a noble court.",
    notes: "",
    tags: ["charisma", "social"]
  },
  {
    id: "skill-persuasion",
    linkId: "persuasion",
    name: "Persuasion",
    defaultAbility: "Charisma",
    source: "Player's Handbook",
    page: "",
    summary: "Influence with tact and social grace.",
    description: "When you attempt to influence someone or a group of people with tact, social graces, or good nature, the GM might ask you to make a Charisma (Persuasion) check.",
    typicalUses: "Diplomacy, negotiation, appeals to reason or friendship.",
    exampleChecks: "Broker peace; convince a merchant to lower a price; sway a council.",
    notes: "",
    tags: ["charisma", "social"]
  },
  {
    id: "skill-religion",
    linkId: "religion",
    name: "Religion",
    defaultAbility: "Intelligence",
    source: "Player's Handbook",
    page: "",
    summary: "Knowledge of deities, rites, and holy symbols.",
    description: "Your Intelligence (Religion) check measures your ability to recall lore about deities, rites and prayers, religious hierarchies, holy symbols, and the practices of secret cults.",
    typicalUses: "Identify cults, holy symbols, rites, divine lore.",
    exampleChecks: "Recognize a desecrated altar; recall a god's dogma; identify undead origins.",
    notes: "",
    tags: ["intelligence", "divine"]
  },
  {
    id: "skill-sleight-of-hand",
    linkId: "sleight-of-hand",
    name: "Sleight of Hand",
    defaultAbility: "Dexterity",
    source: "Player's Handbook",
    page: "",
    summary: "Plant, conceal, or steal small objects.",
    description: "Whenever you attempt an act of legerdemain or manual trickery, such as planting something on someone else or concealing an object on your person, make a Dexterity (Sleight of Hand) check.",
    typicalUses: "Pick pockets, palm objects, plant evidence, subtle juggling.",
    exampleChecks: "Lift a keyring; hide a potion; switch identical vials.",
    notes: "",
    tags: ["dexterity", "stealth"]
  },
  {
    id: "skill-stealth",
    linkId: "stealth",
    name: "Stealth",
    defaultAbility: "Dexterity",
    source: "Player's Handbook",
    page: "",
    summary: "Conceal yourself from enemies and observers.",
    description: "Make a Dexterity (Stealth) check when you attempt to conceal yourself from enemies, slink past guards, slip away without being noticed, or sneak up on someone without being seen or heard.",
    typicalUses: "Hide, sneak, ambush approach.",
    exampleChecks: "Slip past sentries; hide in underbrush; approach a camp unseen.",
    notes: "",
    tags: ["dexterity", "stealth"]
  },
  {
    id: "skill-survival",
    linkId: "survival",
    name: "Survival",
    defaultAbility: "Wisdom",
    source: "Player's Handbook",
    page: "",
    summary: "Follow tracks, hunt, and navigate wilderness.",
    description: "The GM might ask you to make a Wisdom (Survival) check to follow tracks, hunt wild game, guide your group through frozen wastelands, identify signs that owlbears live nearby, predict the weather, or avoid quicksand and other natural hazards.",
    typicalUses: "Track, forage, navigate, predict weather, wilderness hazards.",
    exampleChecks: "Follow a creature's trail; find fresh water; avoid a bog.",
    notes: "",
    tags: ["wisdom", "wilderness"]
  }
];
