/**
 * Core race & class catalogue seeds (5e-style reference starters).
 * Merged into localStorage on first open (missing IDs only).
 * Campaign-agnostic — safe to load alongside Stormwreck seeds.
 *
 * Taxonomy: species/subspecies (@race:), class/subclass (@class:).
 */
window.CatalogueSeeds = window.CatalogueSeeds || {};

window.CatalogueSeeds.race = [
  {
    "id": "race-dwarf",
    "name": "Dwarf",
    "size": "Medium",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Stout folk of stone and forge — hardy, traditional, and hard to poison.",
    "abilityScoreIncrease": "CON +2 (see subspecies for additional ASI)",
    "traits": "Darkvision 60 ft.\nDwarven Resilience — advantage on saves vs poison; resistance to poison damage.\nDwarven Combat Training — battleaxe, handaxe, light hammer, warhammer.\nTool Proficiency — smith, brewer, or mason tools.\nStonecunning — History checks related to stonework use double proficiency.",
    "languages": "Common, Dwarvish",
    "senses": "Darkvision 60 ft.",
    "notes": "Choose a subspecies: Hill Dwarf or Mountain Dwarf.",
    "entryKind": "species",
    "subspeciesRefs": [
      "@race:subspecies-dwarf-hill|Hill Dwarf",
      "@race:subspecies-dwarf-mountain|Mountain Dwarf"
    ]
  },
  {
    "id": "race-elf",
    "name": "Elf",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Graceful folk of keen senses and long lives — trance instead of sleep.",
    "abilityScoreIncrease": "DEX +2 (see subspecies for additional ASI)",
    "featureRefs": [
      "@feature:darkvision|Darkvision",
      "@feature:keen-senses|Keen Senses",
      "@feature:fey-ancestry|Fey Ancestry",
      "@feature:trance|Trance"
    ],
    "traits": "Base elf traits via featureRefs. Subspecies add weapon training, magic, or speed options.",
    "languages": "Common, Elvish",
    "senses": "Darkvision 60 ft. (drow: 120 ft. — see subspecies)",
    "notes": "Choose a subspecies: High Elf, Wood Elf, or Drow.",
    "entryKind": "species",
    "subspeciesRefs": [
      "@race:subspecies-elf-high|High Elf",
      "@race:subspecies-elf-wood|Wood Elf",
      "@race:subspecies-elf-drow|Drow (Dark Elf)"
    ]
  },
  {
    "id": "race-halfling",
    "name": "Halfling",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Small, lucky wanderers — brave when it counts, hard to pin down.",
    "abilityScoreIncrease": "DEX +2 (see subspecies for additional ASI)",
    "traits": "Lucky — reroll natural 1s on attack rolls, ability checks, and saving throws (must use new roll).\nBrave — advantage on saves vs frightened.\nHalfling Nimbleness — move through the space of any creature larger than you.",
    "languages": "Common, Halfling",
    "senses": "",
    "notes": "Choose a subspecies: Lightfoot or Stout.",
    "entryKind": "species",
    "subspeciesRefs": [
      "@race:subspecies-halfling-lightfoot|Lightfoot Halfling",
      "@race:subspecies-halfling-stout|Stout Halfling"
    ]
  },
  {
    "id": "race-human",
    "name": "Human",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Versatile and ambitious — the most adaptable of the common folk.",
    "abilityScoreIncrease": "All abilities +1 (variant: two +1s, one skill, one feat)",
    "traits": "Standard: +1 to each ability score; one extra language.\nVariant (if allowed): +1 to two abilities, proficiency in one skill, one feat.",
    "languages": "Common + one of your choice",
    "senses": "",
    "notes": "Ask whether the table uses standard or variant humans.",
    "entryKind": "species",
    "subspeciesRefs": []
  },
  {
    "id": "race-dragonborn",
    "name": "Dragonborn",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Draconic humanoids with breath weapons and elemental resistance.",
    "abilityScoreIncrease": "STR +2, CHA +1",
    "traits": "Draconic Ancestry — choose a dragon type (damage type for breath & resistance).\nBreath Weapon — action; 15-ft cone or 30-ft line (by ancestry); DEX save; 2d6 then scales with level; 1/rest.\nDamage Resistance — matching ancestry damage type.",
    "languages": "Common, Draconic",
    "senses": "",
    "notes": "Ancestry table: acid, lightning, fire, poison, or cold depending on color.",
    "entryKind": "species",
    "subspeciesRefs": []
  },
  {
    "id": "race-gnome",
    "name": "Gnome",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Small inventors and illusionists — curious, clever, and hard to charm.",
    "abilityScoreIncrease": "INT +2 (see subspecies for additional ASI)",
    "traits": "Darkvision 60 ft.\nGnome Cunning — advantage on INT/WIS/CHA saves vs magic.",
    "languages": "Common, Gnomish",
    "senses": "Darkvision 60 ft.",
    "notes": "Choose a subspecies: Forest Gnome or Rock Gnome.",
    "entryKind": "species",
    "subspeciesRefs": [
      "@race:subspecies-gnome-forest|Forest Gnome",
      "@race:subspecies-gnome-rock|Rock Gnome"
    ]
  },
  {
    "id": "race-half-elf",
    "name": "Half-Elf",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Caught between two worlds — charismatic and adaptable.",
    "abilityScoreIncrease": "CHA +2; two other abilities +1 each",
    "traits": "Darkvision 60 ft.\nFey Ancestry — advantage vs charmed; magic can't put you to sleep.\nSkill Versatility — proficiency in two skills of your choice.",
    "languages": "Common, Elvish + one of your choice",
    "senses": "Darkvision 60 ft.",
    "notes": "",
    "entryKind": "species",
    "subspeciesRefs": []
  },
  {
    "id": "race-half-orc",
    "name": "Half-Orc",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Fierce survivors marked by orcish endurance and relentless grit.",
    "abilityScoreIncrease": "STR +2, CON +1",
    "traits": "Darkvision 60 ft.\nMenacing — Intimidation proficiency.\nRelentless Endurance — once per long rest, drop to 1 HP instead of 0.\nSavage Attacks — extra damage die on critical melee weapon hits.",
    "languages": "Common, Orc",
    "senses": "Darkvision 60 ft.",
    "notes": "",
    "entryKind": "species",
    "subspeciesRefs": []
  },
  {
    "id": "race-tiefling",
    "name": "Tiefling",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Infernal heritage shows in horns, tails, and innate fire magic.",
    "abilityScoreIncrease": "CHA +2, INT +1",
    "traits": "Darkvision 60 ft.\nHellish Resistance — fire resistance.\nInfernal Legacy — thaumaturgy; at 3rd hellish rebuke (1/long rest); at 5th darkness (1/long rest); CHA spellcasting.",
    "languages": "Common, Infernal",
    "senses": "Darkvision 60 ft.",
    "notes": "",
    "entryKind": "species",
    "subspeciesRefs": []
  },
  {
    "id": "subspecies-dwarf-hill",
    "name": "Hill Dwarf",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-dwarf|Dwarf",
    "size": "Medium",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Hill dwarves favor wisdom and tough constitutions.",
    "abilityScoreIncrease": "WIS +1 (plus Dwarf CON +2)",
    "featureRefs": [],
    "traits": "Dwarven Toughness — your hit point maximum increases by 1, and it increases by 1 every time you gain a level.",
    "languages": "Common, Dwarvish",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-dwarf-mountain",
    "name": "Mountain Dwarf",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-dwarf|Dwarf",
    "size": "Medium",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Mountain dwarves are stronger and trained in armor from youth.",
    "abilityScoreIncrease": "STR +2 (plus Dwarf CON +2)",
    "featureRefs": [],
    "traits": "Dwarven Armor Training — proficiency with light and medium armor.",
    "languages": "Common, Dwarvish",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-elf-high",
    "name": "High Elf",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-elf|Elf",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "High elves blend martial tradition with arcane study.",
    "abilityScoreIncrease": "INT +1 (plus Elf DEX +2)",
    "featureRefs": [],
    "traits": "Elf Weapon Training — longsword, shortsword, shortbow, longbow.\nCantrip — one wizard cantrip (INT).\nExtra Language — one extra language of your choice.",
    "languages": "Common, Elvish + one of your choice",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-elf-wood",
    "name": "Wood Elf",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-elf|Elf",
    "size": "Medium",
    "speed": "35 ft.",
    "source": "Core rules",
    "summary": "Wood elves move swiftly and vanish into natural cover.",
    "abilityScoreIncrease": "WIS +1 (plus Elf DEX +2)",
    "featureRefs": [],
    "traits": "Elf Weapon Training — longsword, shortsword, shortbow, longbow.\nFleet of Foot — base walking speed 35 ft.\nMask of the Wild — hide when lightly obscured by natural phenomena.",
    "languages": "Common, Elvish",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-elf-drow",
    "name": "Drow (Dark Elf)",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-elf|Elf",
    "size": "Medium",
    "speed": "30 ft.",
    "source": "Core rules",
    "summary": "Underdark elves with superior darkvision and innate magic.",
    "abilityScoreIncrease": "CHA +1 (plus Elf DEX +2)",
    "featureRefs": [],
    "traits": "Superior Darkvision — 120 ft.\nSunlight Sensitivity — disadvantage on attacks and Perception (sight) in sunlight.\nDrow Magic — dancing lights; at 3rd faerie fire 1/long rest; at 5th darkness 1/long rest (CHA).\nDrow Weapon Training — rapiers, shortswords, hand crossbows.",
    "languages": "Common, Elvish",
    "senses": "Darkvision 120 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-halfling-lightfoot",
    "name": "Lightfoot Halfling",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-halfling|Halfling",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Lightfoots are especially stealthy and charismatic.",
    "abilityScoreIncrease": "CHA +1 (plus Halfling DEX +2)",
    "featureRefs": [],
    "traits": "Naturally Stealthy — you can attempt to hide behind a creature that is at least one size larger than you.",
    "languages": "Common, Halfling",
    "senses": "",
    "notes": ""
  },
  {
    "id": "subspecies-halfling-stout",
    "name": "Stout Halfling",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-halfling|Halfling",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Stout halflings share some dwarven hardiness against poison.",
    "abilityScoreIncrease": "CON +1 (plus Halfling DEX +2)",
    "featureRefs": [],
    "traits": "Stout Resilience — advantage on saving throws against poison, and resistance to poison damage.",
    "languages": "Common, Halfling",
    "senses": "",
    "notes": ""
  },
  {
    "id": "subspecies-gnome-forest",
    "name": "Forest Gnome",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-gnome|Gnome",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Forest gnomes lean into illusion and kinship with small beasts.",
    "abilityScoreIncrease": "DEX +1 (plus Gnome INT +2)",
    "featureRefs": [],
    "traits": "Natural Illusionist — minor illusion cantrip (INT).\nSpeak with Small Beasts — communicate simple ideas with Small or smaller beasts.",
    "languages": "Common, Gnomish",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  },
  {
    "id": "subspecies-gnome-rock",
    "name": "Rock Gnome",
    "entryKind": "subspecies",
    "parentSpeciesRef": "@race:race-gnome|Gnome",
    "size": "Small",
    "speed": "25 ft.",
    "source": "Core rules",
    "summary": "Rock gnomes invent tiny devices and excel with magical technology.",
    "abilityScoreIncrease": "CON +1 (plus Gnome INT +2)",
    "featureRefs": [],
    "traits": "Artificer's Lore — double proficiency on History checks related to magic items, alchemical objects, or technological devices.\nTinker — spend 1 hour and 10 gp to create a Tiny clockwork device (Clockwork Toy, Fire Starter, or Music Box).",
    "languages": "Common, Gnomish",
    "senses": "Darkvision 60 ft.",
    "notes": ""
  }
];

window.CatalogueSeeds.class = [
  {
    "id": "class-barbarian",
    "name": "Barbarian",
    "hitDie": "d12",
    "primaryAbility": "Strength",
    "source": "Core rules",
    "summary": "Primal warriors who channel rage into devastating melee power.",
    "savingThrows": "Strength, Constitution",
    "armorProficiencies": "Light armor, medium armor, shields",
    "weaponProficiencies": "Simple weapons, martial weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from Animal Handling, Athletics, Intimidation, Nature, Perception, Survival",
    "features": "1 — Rage, Unarmored Defense\n2 — Reckless Attack, Danger Sense\n3 — Primal Path\n5 — Extra Attack, Fast Movement\n7 — Feral Instinct\n9 — Brutal Critical\n11 — Relentless Rage\n13+ — path features & Brutal Critical improvements",
    "spellcasting": "",
    "notes": "Best when unarmored or lightly armored; rage resists bludgeoning/piercing/slashing while active.",
    "skillRefs": [],
    "featureRefs": [],
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-barbarian-berserker|Path of the Berserker",
      "@class:subclass-barbarian-totem-warrior|Path of the Totem Warrior"
    ]
  },
  {
    "id": "class-bard",
    "name": "Bard",
    "hitDie": "d8",
    "primaryAbility": "Charisma",
    "source": "Core rules",
    "summary": "Magical entertainers who inspire allies and weave spells through performance.",
    "savingThrows": "Dexterity, Charisma",
    "armorProficiencies": "Light armor",
    "weaponProficiencies": "Simple weapons, hand crossbows, longswords, rapiers, shortswords",
    "toolProficiencies": "Three musical instruments",
    "skillChoices": "Choose any 3 skills",
    "features": "1 — Spellcasting, Bardic Inspiration (d6)\n2 — Jack of All Trades, Song of Rest\n3 — Bard College, Expertise\n5 — Font of Inspiration\n6 — Countercharm / college feature\n10 — Magical Secrets\n20 — Superior Inspiration",
    "spellcasting": "Full caster (CHA). Ritual casting. Magical Secrets at 10/14/18.",
    "notes": "",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-bard-lore|College of Lore",
      "@class:subclass-bard-valor|College of Valor"
    ]
  },
  {
    "id": "class-cleric",
    "name": "Cleric",
    "hitDie": "d8",
    "primaryAbility": "Wisdom",
    "source": "Core rules",
    "summary": "Divine agents who heal, protect, and channel their deity's domain power.",
    "savingThrows": "Wisdom, Charisma",
    "armorProficiencies": "Light armor, medium armor, shields",
    "weaponProficiencies": "Simple weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from History, Insight, Medicine, Persuasion, Religion",
    "features": "1 — Spellcasting, Divine Domain\n2 — Channel Divinity (1/rest), Domain feature\n5 — Destroy Undead (CR 1/2)\n6 — Domain feature / Channel Divinity (2)\n8 — Domain feature / Destroy Undead improvement\n10 — Divine Intervention\n17+ — Domain & Destroy Undead scaling",
    "spellcasting": "Full caster (WIS). Prepare from full cleric list each day. Domain spells always prepared.",
    "notes": "Domain choice drives armor/weapon extras and Channel Divinity options.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-cleric-life|Life Domain",
      "@class:subclass-cleric-light|Light Domain",
      "@class:subclass-cleric-nature|Nature Domain",
      "@class:subclass-cleric-tempest|Tempest Domain",
      "@class:subclass-cleric-trickery|Trickery Domain",
      "@class:subclass-cleric-war|War Domain",
      "@class:subclass-cleric-knowledge|Knowledge Domain"
    ]
  },
  {
    "id": "class-druid",
    "name": "Druid",
    "hitDie": "d8",
    "primaryAbility": "Wisdom",
    "source": "Core rules",
    "summary": "Wardens of nature who shapeshift and call on primal magic.",
    "savingThrows": "Intelligence, Wisdom",
    "armorProficiencies": "Light armor, medium armor, shields (nonmetal)",
    "weaponProficiencies": "Clubs, daggers, darts, javelins, maces, quarterstaffs, scimitars, sickles, slings, spears",
    "toolProficiencies": "Herbalism kit",
    "skillChoices": "Choose 2 from the listed skill options",
    "skillRefs": [
      "@skill:arcana|Arcana",
      "@skill:animal-handling|Animal Handling",
      "@skill:insight|Insight",
      "@skill:medicine|Medicine",
      "@skill:nature|Nature",
      "@skill:perception|Perception",
      "@skill:religion|Religion",
      "@skill:survival|Survival"
    ],
    "featureRefs": [
      "@feature:druidic|Druidic",
      "@feature:spellcasting-druid|Spellcasting (Druid)",
      "@feature:wild-shape|Wild Shape"
    ],
    "features": "1 — @feature:druidic|Druidic, @feature:spellcasting-druid|Spellcasting (Druid)\n2 — @feature:wild-shape|Wild Shape, Druid Circle\n4 — Wild Shape improvement\n6+ — circle features\n18 — Timeless Body, Beast Spells\n20 — Archdruid",
    "spellcasting": "Full caster (WIS). Prepare from full druid list. Ritual casting. No metal armor/shields by tradition.",
    "notes": "Wild Shape CR and swim/fly forms unlock by level / circle.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-druid-land|Circle of the Land",
      "@class:subclass-druid-moon|Circle of the Moon"
    ]
  },
  {
    "id": "class-fighter",
    "name": "Fighter",
    "hitDie": "d10",
    "primaryAbility": "Strength or Dexterity",
    "source": "Core rules",
    "summary": "Masters of arms and armor — reliable damage and battlefield control.",
    "savingThrows": "Strength, Constitution",
    "armorProficiencies": "All armor, shields",
    "weaponProficiencies": "Simple weapons, martial weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from the listed skill options",
    "skillRefs": [
      "@skill:acrobatics|Acrobatics",
      "@skill:animal-handling|Animal Handling",
      "@skill:athletics|Athletics",
      "@skill:history|History",
      "@skill:insight|Insight",
      "@skill:intimidation|Intimidation",
      "@skill:perception|Perception",
      "@skill:survival|Survival"
    ],
    "featureRefs": [
      "@feature:second-wind|Second Wind",
      "@feature:action-surge|Action Surge"
    ],
    "features": "1 — Fighting Style, @feature:second-wind|Second Wind\n2 — @feature:action-surge|Action Surge (1)\n3 — Martial Archetype\n5 — Extra Attack\n9 — Indomitable\n11 — Extra Attack (2)\n13+ — Indomitable & archetype improvements\n20 — Extra Attack (3)",
    "spellcasting": "Eldritch Knight only (INT, 1/3 caster).",
    "notes": "",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-fighter-champion|Champion",
      "@class:subclass-fighter-battle-master|Battle Master",
      "@class:subclass-fighter-eldritch-knight|Eldritch Knight"
    ]
  },
  {
    "id": "class-monk",
    "name": "Monk",
    "hitDie": "d8",
    "primaryAbility": "Dexterity & Wisdom",
    "source": "Core rules",
    "summary": "Martial artists who turn ki into speed, strikes, and supernatural movement.",
    "savingThrows": "Strength, Dexterity",
    "armorProficiencies": "None",
    "weaponProficiencies": "Simple weapons, shortswords",
    "toolProficiencies": "One artisan tool or musical instrument",
    "skillChoices": "Choose 2 from Acrobatics, Athletics, History, Insight, Religion, Stealth",
    "features": "1 — Unarmored Defense, Martial Arts\n2 — Ki, Unarmored Movement\n3 — Monastic Tradition, Deflect Missiles\n5 — Extra Attack, Stunning Strike\n6 — Ki-Empowered Strikes / tradition\n7 — Evasion, Stillness of Mind\n10 — Purity of Body\n13 — Tongue of the Sun and Moon\n14 — Diamond Soul\n18 — Empty Body\n20 — Perfect Self",
    "spellcasting": "Way of the Four Elements only (limited elemental disciplines).",
    "notes": "Martial Arts die and Unarmored Movement scale with level.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-monk-open-hand|Way of the Open Hand",
      "@class:subclass-monk-shadow|Way of Shadow",
      "@class:subclass-monk-four-elements|Way of the Four Elements"
    ]
  },
  {
    "id": "class-paladin",
    "name": "Paladin",
    "hitDie": "d10",
    "primaryAbility": "Strength & Charisma",
    "source": "Core rules",
    "summary": "Oath-bound warriors who smite foes and heal with divine power.",
    "savingThrows": "Wisdom, Charisma",
    "armorProficiencies": "All armor, shields",
    "weaponProficiencies": "Simple weapons, martial weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from Athletics, Insight, Intimidation, Medicine, Persuasion, Religion",
    "featureRefs": [
      "@feature:divine-smite|Divine Smite"
    ],
    "features": "1 — Divine Sense, Lay on Hands\n2 — Fighting Style, Spellcasting, @feature:divine-smite|Divine Smite\n3 — Divine Health, Sacred Oath\n5 — Extra Attack\n6 — Aura of Protection\n10 — Aura of Courage\n11 — Improved Divine Smite\n14 — Cleansing Touch\nOath features at 3/7/15/20",
    "spellcasting": "Half caster (CHA). Prepare from paladin list. Oath spells always prepared.",
    "notes": "Divine Smite spends spell slots for radiant damage on hit.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-paladin-devotion|Oath of Devotion",
      "@class:subclass-paladin-ancients|Oath of the Ancients",
      "@class:subclass-paladin-vengeance|Oath of Vengeance"
    ]
  },
  {
    "id": "class-ranger",
    "name": "Ranger",
    "hitDie": "d10",
    "primaryAbility": "Dexterity & Wisdom",
    "source": "Core rules",
    "summary": "Wilderness hunters who track prey and fight with steel or spells.",
    "savingThrows": "Strength, Dexterity",
    "armorProficiencies": "Light armor, medium armor, shields",
    "weaponProficiencies": "Simple weapons, martial weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 3 from Animal Handling, Athletics, Insight, Investigation, Nature, Perception, Stealth, Survival",
    "features": "1 — Favored Enemy, Natural Explorer\n2 — Fighting Style, Spellcasting\n3 — Ranger Archetype, Primeval Awareness\n5 — Extra Attack\n8 — Land's Stride\n10 — Hide in Plain Sight\n14 — Vanish\n18 — Feral Senses\n20 — Foe Slayer",
    "spellcasting": "Half caster (WIS). Known spells (not prepared).",
    "notes": "Optional class features / revised ranger exist at many tables — ask the DM.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-ranger-hunter|Hunter",
      "@class:subclass-ranger-beast-master|Beast Master"
    ]
  },
  {
    "id": "class-rogue",
    "name": "Rogue",
    "hitDie": "d8",
    "primaryAbility": "Dexterity",
    "source": "Core rules",
    "summary": "Skilled infiltrators who strike from advantage and excel at expertise.",
    "savingThrows": "Dexterity, Intelligence",
    "armorProficiencies": "Light armor",
    "weaponProficiencies": "Simple weapons, hand crossbows, longswords, rapiers, shortswords",
    "toolProficiencies": "Thieves' tools",
    "skillChoices": "Choose 4 from Acrobatics, Athletics, Deception, Insight, Intimidation, Investigation, Perception, Performance, Persuasion, Sleight of Hand, Stealth",
    "featureRefs": [
      "@feature:sneak-attack|Sneak Attack"
    ],
    "features": "1 — Expertise, @feature:sneak-attack|Sneak Attack, Thieves' Cant\n2 — Cunning Action\n3 — Roguish Archetype\n5 — Uncanny Dodge\n6 — Expertise\n7 — Evasion\n11 — Reliable Talent\n14 — Blindsense\n15 — Slippery Mind\n18 — Elusive\n20 — Stroke of Luck",
    "spellcasting": "Arcane Trickster only (INT, 1/3 caster).",
    "notes": "Sneak Attack dice scale with level; need finesse/ranged + advantage or ally within 5 ft.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-rogue-thief|Thief",
      "@class:subclass-rogue-assassin|Assassin",
      "@class:subclass-rogue-arcane-trickster|Arcane Trickster"
    ]
  },
  {
    "id": "class-sorcerer",
    "name": "Sorcerer",
    "hitDie": "d6",
    "primaryAbility": "Charisma",
    "source": "Core rules",
    "summary": "Innate spellcasters who twist magic with metamagic and sorcerous origin.",
    "savingThrows": "Constitution, Charisma",
    "armorProficiencies": "None",
    "weaponProficiencies": "Daggers, darts, slings, quarterstaffs, light crossbows",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from Arcana, Deception, Insight, Intimidation, Persuasion, Religion",
    "features": "1 — Spellcasting, Sorcerous Origin\n2 — Font of Magic (sorcery points)\n3 — Metamagic\n6+ — origin features\n20 — Sorcerous Restoration",
    "spellcasting": "Full caster (CHA). Known spells. Sorcery points fuel metamagic and slot conversion.",
    "notes": "",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-sorcerer-draconic|Draconic Bloodline",
      "@class:subclass-sorcerer-wild-magic|Wild Magic"
    ]
  },
  {
    "id": "class-warlock",
    "name": "Warlock",
    "hitDie": "d8",
    "primaryAbility": "Charisma",
    "source": "Core rules",
    "summary": "Pact-bound casters with few slots that refresh on a short rest — plus invocations.",
    "savingThrows": "Wisdom, Charisma",
    "armorProficiencies": "Light armor",
    "weaponProficiencies": "Simple weapons",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from Arcana, Deception, History, Intimidation, Investigation, Nature, Religion",
    "features": "1 — Otherworldly Patron, Pact Magic\n2 — Eldritch Invocations\n3 — Pact Boon\n6+ — patron features\n11 — Mystic Arcanum (6th)\n17 — Mystic Arcanum (9th)\n20 — Eldritch Master",
    "spellcasting": "Pact Magic (CHA). Few slots, all at same level, recover on short rest. Invocations expand options.",
    "notes": "Pact Boons: Chain, Blade, or Tome.",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-warlock-archfey|The Archfey",
      "@class:subclass-warlock-fiend|The Fiend",
      "@class:subclass-warlock-great-old-one|The Great Old One"
    ]
  },
  {
    "id": "class-wizard",
    "name": "Wizard",
    "hitDie": "d6",
    "primaryAbility": "Intelligence",
    "source": "Core rules",
    "summary": "Scholarly casters who prepare from a spellbook and specialize by arcane tradition.",
    "savingThrows": "Intelligence, Wisdom",
    "armorProficiencies": "None",
    "weaponProficiencies": "Daggers, darts, slings, quarterstaffs, light crossbows",
    "toolProficiencies": "",
    "skillChoices": "Choose 2 from Arcana, History, Insight, Investigation, Medicine, Religion",
    "features": "1 — Spellcasting, Arcane Recovery\n2 — Arcane Tradition\n6+ — tradition features\n18 — Spell Mastery\n20 — Signature Spells",
    "spellcasting": "Full caster (INT). Spellbook; prepare INT mod + wizard level spells each day. Ritual casting from book.",
    "notes": "Copying spells into the book costs time and gold; Arcane Recovery restores slots on a short rest (1/day).",
    "entryKind": "class",
    "subclassRefs": [
      "@class:subclass-wizard-abjuration|School of Abjuration",
      "@class:subclass-wizard-conjuration|School of Conjuration",
      "@class:subclass-wizard-divination|School of Divination",
      "@class:subclass-wizard-enchantment|School of Enchantment",
      "@class:subclass-wizard-evocation|School of Evocation",
      "@class:subclass-wizard-illusion|School of Illusion",
      "@class:subclass-wizard-necromancy|School of Necromancy",
      "@class:subclass-wizard-transmutation|School of Transmutation"
    ]
  },
  {
    "id": "subclass-barbarian-berserker",
    "name": "Path of the Berserker",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-barbarian|Barbarian",
    "source": "Core rules",
    "summary": "Frenzied rage for reckless offense at the cost of exhaustion.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-barbarian-totem-warrior",
    "name": "Path of the Totem Warrior",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-barbarian|Barbarian",
    "source": "Core rules",
    "summary": "Spirit totems grant defensive, offensive, or utility benefits while raging.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-bard-lore",
    "name": "College of Lore",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-bard|Bard",
    "source": "Core rules",
    "summary": "Cutting Words and Magical Secrets — versatile knowledge and spell theft.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-bard-valor",
    "name": "College of Valor",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-bard|Bard",
    "source": "Core rules",
    "summary": "Martial college with Combat Inspiration, armor, and Extra Attack.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-life",
    "name": "Life Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Supreme healing domain — Disciple of Life and Preserve Life.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-light",
    "name": "Light Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Radiant and fire magic with Warding Flare.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-nature",
    "name": "Nature Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Druid cantrip and heavy armor options tied to nature deities.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-tempest",
    "name": "Tempest Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Thunder and lightning domain with Wrath of the Storm.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-trickery",
    "name": "Trickery Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Illusion and deception — Blessing of the Trickster and Invoke Duplicity.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-war",
    "name": "War Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Martial cleric with War Priest bonus attacks and Divine Strike.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-cleric-knowledge",
    "name": "Knowledge Domain",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-cleric|Cleric",
    "source": "Core rules",
    "summary": "Expertise in knowledge skills and Read Thoughts Channel Divinity.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-druid-land",
    "name": "Circle of the Land",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-druid|Druid",
    "source": "Core rules",
    "summary": "Terrain spell lists, Natural Recovery, and Land's Stride.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-druid-moon",
    "name": "Circle of the Moon",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-druid|Druid",
    "source": "Core rules",
    "summary": "Combat Wild Shape into stronger beasts and later elemental forms.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-fighter-champion",
    "name": "Champion",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-fighter|Fighter",
    "source": "Core rules",
    "summary": "Improved Critical and reliable athletic prowess.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-fighter-battle-master",
    "name": "Battle Master",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-fighter|Fighter",
    "source": "Core rules",
    "summary": "Maneuvers fueled by superiority dice for battlefield control.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-fighter-eldritch-knight",
    "name": "Eldritch Knight",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-fighter|Fighter",
    "source": "Core rules",
    "summary": "1/3 wizard spellcasting bonded to weapons.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-monk-open-hand",
    "name": "Way of the Open Hand",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-monk|Monk",
    "source": "Core rules",
    "summary": "Flurry control effects and Quivering Palm.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-monk-shadow",
    "name": "Way of Shadow",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-monk|Monk",
    "source": "Core rules",
    "summary": "Shadow arts teleportation and darkness magic.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-monk-four-elements",
    "name": "Way of the Four Elements",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-monk|Monk",
    "source": "Core rules",
    "summary": "Spend ki on elemental disciplines resembling spells.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-paladin-devotion",
    "name": "Oath of Devotion",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-paladin|Paladin",
    "source": "Core rules",
    "summary": "Sacred Weapon and Turn the Unholy — classic righteous knight.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-paladin-ancients",
    "name": "Oath of the Ancients",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-paladin|Paladin",
    "source": "Core rules",
    "summary": "Nature-bound oath with Nature's Wrath and Aura of Warding.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-paladin-vengeance",
    "name": "Oath of Vengeance",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-paladin|Paladin",
    "source": "Core rules",
    "summary": "Hunter of wrongdoers — Vow of Enmity and Relentless Avenger.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-ranger-hunter",
    "name": "Hunter",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-ranger|Ranger",
    "source": "Core rules",
    "summary": "Choose Colossus Slayer, Giant Killer, or Horde Breaker features.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-ranger-beast-master",
    "name": "Beast Master",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-ranger|Ranger",
    "source": "Core rules",
    "summary": "Bonded beast companion that fights beside you.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-rogue-thief",
    "name": "Thief",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-rogue|Rogue",
    "source": "Core rules",
    "summary": "Fast Hands and Second-Story Work for infiltration.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-rogue-assassin",
    "name": "Assassin",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-rogue|Rogue",
    "source": "Core rules",
    "summary": "Assassinate on surprised foes; disguise and poison tools.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-rogue-arcane-trickster",
    "name": "Arcane Trickster",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-rogue|Rogue",
    "source": "Core rules",
    "summary": "1/3 wizard spellcasting focused on enchantment and illusion.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-sorcerer-draconic",
    "name": "Draconic Bloodline",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-sorcerer|Sorcerer",
    "source": "Core rules",
    "summary": "Draconic resilience, Elemental Affinity, and dragon wings.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-sorcerer-wild-magic",
    "name": "Wild Magic",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-sorcerer|Sorcerer",
    "source": "Core rules",
    "summary": "Wild Magic Surge table and Tides of Chaos.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-warlock-archfey",
    "name": "The Archfey",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-warlock|Warlock",
    "source": "Core rules",
    "summary": "Fey patron — Fey Presence and misty escape options.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-warlock-fiend",
    "name": "The Fiend",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-warlock|Warlock",
    "source": "Core rules",
    "summary": "Fiendish patron — Dark One's Blessing temporary HP.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-warlock-great-old-one",
    "name": "The Great Old One",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-warlock|Warlock",
    "source": "Core rules",
    "summary": "Alien patron — telepathy and thought-warping features.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-abjuration",
    "name": "School of Abjuration",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Arcane Ward absorbs damage; abjuration specialists.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-conjuration",
    "name": "School of Conjuration",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Minor Conjuration and Benign Transposition.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-divination",
    "name": "School of Divination",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Portent dice rewrite rolls; third eye senses.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-enchantment",
    "name": "School of Enchantment",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Hypnotic Gaze and instinctive charm defenses.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-evocation",
    "name": "School of Evocation",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Sculpt Spells and empowered blast damage.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-illusion",
    "name": "School of Illusion",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Improved minor illusion and malleable illusions.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-necromancy",
    "name": "School of Necromancy",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Grim Harvest and undead thrall control.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  },
  {
    "id": "subclass-wizard-transmutation",
    "name": "School of Transmutation",
    "entryKind": "subclass",
    "parentClassRef": "@class:class-wizard|Wizard",
    "source": "Core rules",
    "summary": "Transmuter's Stone and shapechanging mastery.",
    "featureRefs": [],
    "features": "",
    "spellcasting": "",
    "notes": ""
  }
];
