/**
 * Stormwreck Isle — default NPC, monster, item & location catalogue entries from the booklet.
 * Merged into localStorage on first load (missing IDs only).
 */
window.CatalogueSeeds = {
  npc: [
    {
      id: "sw-runara",
      name: "Elder Runara",
      role: "Cloister leader (adult bronze dragon in human form)",
      race: "Bronze dragon (human form)",
      alignment: "Lawful good",
      age: "Centuries old",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest",
      str: 25,
      dex: 10,
      con: 23,
      int: 16,
      wis: 15,
      cha: 19,
      ac: "18 (natural armor)",
      hp: "142 (19d10+38)",
      speed: "40 ft., fly 80 ft., swim 40 ft.",
      traits: "Wise, patient, protective of the cloister. Appears as an elderly human with white hair in tight braids.",
      ideals: "Peace between chromatic and metallic dragons; redemption for those shaped by violence.",
      bonds: "Dragon's Rest and its residents. The island's lingering draconic magic.",
      flaws: "Reluctant to reveal her true nature; may intervene only when the party is truly defeated.",
      equipment: ["Simple white robe", "Moonstone key (given to party when ready)"],
      summary: "Leads Dragon's Rest — secretly an adult bronze dragon. Killed a blue dragon here a century ago and founded the cloister as sanctuary.",
      backstory: "A century ago Runara pleaded with a blue dragon to stop harnessing the island's destructive magic. When he refused, she killed him. Weary of strife, she founded Dragon's Rest. She dreams of peace between dragon kind.",
      notes: "Attitude: Indifferent → friendly if party protects cloister or takes quests. Hostile if they harm residents.\n\nSecret lair via undersea tunnel (not on map). Never seems to sleep.\n\nCan rescue a defeated party — use sparingly."
    },
    {
      id: "sw-tarak",
      name: "Tarak",
      role: "Botanist & gardener",
      race: "Human",
      alignment: "Neutral (friendly)",
      age: "Middle-aged",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest — gardens",
      str: 10,
      dex: 12,
      con: 12,
      int: 14,
      wis: 13,
      cha: 11,
      ac: "12 (leather armor)",
      hp: "16 (3d8+3)",
      speed: "30 ft.",
      traits: "Kindly, generous with herbalism knowledge. Becomes cold if pressed about his past.",
      ideals: "Growth and healing through nature.",
      bonds: "The cloister gardens. Sinensa and the myconids (via mushroom offerings).",
      flaws: "Hides a criminal past as a poisoner for the Gilded Gallows thieves' guild.",
      equipment: ["Herbalism kit", "Gardening tools", "Heart cap mushroom offering (for myconids)"],
      summary: "Tends the cloister gardens. Former poisoner — Gilded Gallows tattoos (DC 15 History to recognize).",
      backstory: "Once a poisoner for the Gilded Gallows. Found refuge at Dragon's Rest and reinvented himself as a botanist.",
      notes: "Quest: Needs heart cap mushrooms from Seagrow Caves — blocked by spore servant octopus.\n\nMentioning Tarak or his offering grants advantage on DC 20 Charisma checks with myconids."
    },
    {
      id: "sw-varnoth",
      name: "Varnoth",
      role: "Former general",
      race: "Human",
      alignment: "Lawful neutral",
      age: "Elderly",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest",
      str: 14,
      dex: 12,
      con: 14,
      int: 12,
      wis: 14,
      cha: 10,
      ac: "14 (leather armor)",
      hp: "32 (5d8+10)",
      speed: "30 ft.",
      traits: "Gruff exterior, empathetic listener. Believes in second chances.",
      ideals: "Understanding the consequences of violence.",
      bonds: "The Azure Wolves (former company). The cloister's contemplative life.",
      flaws: "Can seem dismissive until a topic earns her respect.",
      equipment: ["Worn military cloak", "Walking stick"],
      summary: "General Varnoth Wender — led the Azure Wolves mercenary company. Now in contemplative retirement.",
      backstory: "Spent decades as a mercenary general. Witnessed too much war and came to Dragon's Rest seeking peace.",
      notes: "Attitude: Indifferent → friendly when discussing history, ethics, or impact of actions.\n\nWitness: Saw the most recent shipwreck north of the island (with Rix)."
    },
    {
      id: "sw-myla",
      name: "Myla",
      role: "Inventor & equipment vendor",
      race: "Winged kobold",
      alignment: "Lawful good",
      age: "Young adult",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest",
      str: 7,
      dex: 14,
      con: 9,
      int: 16,
      wis: 10,
      cha: 12,
      ac: "14",
      hp: "7 (3d6-3)",
      speed: "30 ft., fly 30 ft. (injured wings)",
      traits: "Energetic inventor, lawful good. Calls stirges 'hungry, icky, blood-sucking bat-things.'",
      ideals: "Progress through clever tinkering and alchemy.",
      bonds: "Laylee (helper). Her injured wings from a stirge attack.",
      flaws: "Heartbroken that brothers Mek and Minn follow Sparkrender.",
      equipment: ["Alchemy supplies", "Standard adventuring gear for sale", "Experimental devices"],
      summary: "Winged kobold tinkerer who sells equipment. Brothers defected to Sparkrender.",
      backstory: "One of nine lawful good kobolds at the cloister. Injured wings limit her flight. Experiments with alchemy — Laylee is banned from using alchemical fire.",
      notes: "Sells equipment from the rulebook. Brothers Mek and Minn are at the observatory with blue face paint."
    },
    {
      id: "sw-mek",
      name: "Mek",
      role: "Sparkrender's kobold follower",
      race: "Kobold",
      alignment: "Lawful good (misguided)",
      age: "Young",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Clifftop Observatory (D2 rotunda)",
      str: 7,
      dex: 15,
      con: 9,
      int: 10,
      wis: 9,
      cha: 10,
      ac: "13",
      hp: "7 (3d6-3)",
      speed: "30 ft., fly 30 ft.",
      traits: "Blue face paint. Fighting stirges when party arrives.",
      ideals: "Loyalty to Sparkrender (misplaced).",
      bonds: "Brother Minn. Sister Myla at the cloister.",
      flaws: "Follows Sparkrender despite good alignment — can be turned if party helps them.",
      equipment: ["Blue face paint", "Light crossbow"],
      summary: "Myla's brother — loyal to Sparkrender. Found at observatory rotunda vs stirges.",
      backstory: "Left Dragon's Rest with Minn to follow the blue wyrmling's cause.",
      notes: "If party helps vs 6 stirges → friendly. May offer to fetch the moonstone key."
    },
    {
      id: "sw-minn",
      name: "Minn",
      role: "Sparkrender's kobold follower",
      race: "Kobold",
      alignment: "Lawful good (misguided)",
      age: "Young",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Clifftop Observatory (D2 rotunda)",
      str: 7,
      dex: 15,
      con: 9,
      int: 10,
      wis: 9,
      cha: 10,
      ac: "13",
      hp: "7 (3d6-3)",
      speed: "30 ft., fly 30 ft.",
      traits: "Blue face paint. Paired with Mek at the rotunda.",
      ideals: "Brotherhood with Mek.",
      bonds: "Brother Mek. Sister Myla.",
      flaws: "Easily swayed by dragon charisma.",
      equipment: ["Blue face paint", "Dagger"],
      summary: "Myla's brother — with Mek at the observatory.",
      backstory: "Followed Sparkrender alongside Mek.",
      notes: "Same encounter as Mek — help against stirges to gain allies."
    },
    {
      id: "sw-sinensa",
      name: "Sinensa",
      role: "Myconid leader",
      race: "Myconid",
      alignment: "Neutral",
      age: "Adult",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Seagrow Caves",
      str: 12,
      dex: 10,
      con: 14,
      int: 10,
      wis: 13,
      cha: 7,
      ac: "13 (natural armor)",
      hp: "22 (3d8+9)",
      speed: "20 ft.",
      traits: "Communicates via rapport spores. Currently unconscious/ill.",
      ideals: "Protect the colony from the fire-plane connection.",
      bonds: "Myconid colony in Seagrow Caves.",
      flaws: "Cannot act while ill from investigating B6 crystal cave.",
      equipment: [],
      summary: "Myconid sovereign — lies ill after investigating the crystal cave (B6).",
      backstory: "Led the myconids until exposure to sulfur and the Elemental Plane of Fire link at Sharruth's grave weakened her.",
      notes: "Party may need to heal or help her. Crystal cave (B6) is source of fire-plane connection."
    },
    {
      id: "sw-aidron",
      name: "Aidron",
      role: "Imprisoned bronze wyrmling",
      race: "Bronze dragon wyrmling",
      alignment: "Chaotic good",
      age: "Wyrmling",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Clifftop Observatory tower (prisoner)",
      str: 17,
      dex: 10,
      con: 15,
      int: 12,
      wis: 11,
      cha: 15,
      ac: "17 (natural armor)",
      hp: "32 (5d8+10)",
      speed: "30 ft., fly 60 ft., swim 30 ft.",
      traits: "Defiant toward chromatic dragons. May ally if freed.",
      ideals: "Opposes Sparkrender's ritual.",
      bonds: "Runara (mentor at Dragon's Rest).",
      flaws: "Imprisoned and weakened — Sparkrender plans to sacrifice him.",
      equipment: [],
      summary: "Bronze wyrmling prisoner — key to Sparkrender's ritual. Left Runara's tutelage ~5 days before party arrival.",
      backstory: "Met Sparkrender at the observatory and refused to join him. Was overpowered and imprisoned. Sparkrender believes Aidron must be sacrificed to bind dead dragon spirits.",
      notes: "Freeing Aidron may turn the finale. Hatred of chromatic dragons stronger than disagreement with Runara."
    },
    {
      id: "sw-laylee",
      name: "Laylee",
      role: "Myla's alchemical assistant",
      race: "Kobold",
      alignment: "Lawful good",
      age: "Young",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest",
      str: 7,
      dex: 14,
      con: 10,
      int: 12,
      wis: 10,
      cha: 11,
      ac: "13",
      hp: "5 (2d6-2)",
      speed: "30 ft.",
      traits: "Enthusiastic but banned from alchemical fire after an incident.",
      ideals: "Help Myla's inventions succeed.",
      bonds: "Myla.",
      flaws: "Overconfident with dangerous reagents.",
      equipment: ["Alchemy apprentice tools"],
      summary: "Myla's helper — banned from using alchemical fire.",
      backstory: "One of the nine cloister kobolds. Works nights due to sunlight sensitivity.",
      notes: "Pick 1–2 kobolds to focus on from the roster — don't need all nine at the table."
    },
    {
      id: "sw-rix",
      name: "Rix",
      role: "Temple attendant",
      race: "Kobold",
      alignment: "Lawful good",
      age: "Adult",
      activeCampaign: "Dragons of Stormwreck Isle",
      location: "Dragon's Rest — temple",
      str: 7,
      dex: 12,
      con: 10,
      int: 11,
      wis: 12,
      cha: 13,
      ac: "12",
      hp: "5 (2d6-2)",
      speed: "30 ft.",
      traits: "Loves puns. Tends the temple.",
      ideals: "Honor Bahamut through service.",
      bonds: "The cloister temple.",
      flaws: "Cannot resist a good (or bad) pun.",
      equipment: ["Temple robes", "Incense"],
      summary: "Tends the temple. Saw the shipwreck with Varnoth.",
      backstory: "Witnessed the latest ship crash north of the cloister.",
      notes: "With Varnoth, points party toward the Compass Rose wreck quest."
    }
  ],

  monster: [
    {
      id: "sw-sparkrender",
      name: "Sparkrender",
      size: "Medium",
      creatureType: "Dragon",
      alignment: "Lawful evil",
      cr: "3",
      xp: "700",
      str: 17,
      dex: 10,
      con: 15,
      int: 12,
      wis: 11,
      cha: 15,
      ac: "17 (natural armor)",
      hp: "52 (8d8+16)",
      speed: "30 ft., burrow 15 ft., fly 60 ft.",
      savingThrows: "Dex +2, Con +4, Wis +2, Cha +4",
      skills: "Perception +4, Stealth +2",
      damageImmunities: "Lightning",
      senses: "Blindsight 10 ft., darkvision 60 ft., passive Perception 14",
      languages: "Draconic",
      traits: "Final boss at Clifftop Observatory (D5–D6). Skinny for a wyrmling; scales glitter; lightning arcs around horns and snout.\n\nPlans a ritual when the King-Killer Star comet is nearest — bind spirits of dead dragons using Aidron as sacrifice.\n\nHas a dozen+ kobold minions. Can negotiate but is cruel and haughty.",
      actions: "Multiattack: One bite attack.\n\nBite. Melee Weapon Attack: +5 to hit, reach 5 ft., one target. Hit: 8 (1d10+3) piercing damage plus 3 (1d6) lightning damage.\n\nLightning Breath (Recharge 5–6). 30-foot line, 5 ft. wide. DC 12 Dex save or 22 (4d10) lightning damage, half on success.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Blue dragon wyrmling — grandson of the dragon Runara killed. Adjust HP/attacks for party size (Sly Flourish recommends dials for 4+ PCs).\n\nPrisoner: Aidron (bronze wyrmling) in the tower."
    },
    {
      id: "sw-zombie",
      name: "Zombie",
      size: "Medium",
      creatureType: "Undead",
      alignment: "Neutral evil",
      cr: "1/4",
      xp: "50",
      str: 13,
      dex: 6,
      con: 16,
      int: 3,
      wis: 6,
      cha: 5,
      ac: "8",
      hp: "22 (3d8+9)",
      speed: "20 ft.",
      savingThrows: "Wis +0",
      skills: "",
      damageImmunities: "Poison",
      conditionImmunities: "Poisoned",
      senses: "Darkvision 60 ft., passive Perception 8",
      languages: "Understands languages it knew in life but can't speak",
      traits: "Undead Fortitude. If damage reduces the zombie to 0 HP, it makes a Con save (DC 5 + damage taken) unless the damage is radiant or a critical hit. On success, drops to 1 HP instead.",
      actions: "Slam. Melee Weapon Attack: +3 to hit, reach 5 ft., one target. Hit: 4 (1d6+1) bludgeoning damage.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Drowned sailors on the beach (Ch 1). Hard to put down without radiant damage or crits.\n\nCompass Rose: 2 in C4 captain's quarters; 1 in C8 lower deck. New zombies stop when hold curse is broken."
    },
    {
      id: "sw-stirge",
      name: "Stirge",
      size: "Tiny",
      creatureType: "Beast",
      alignment: "Unaligned",
      cr: "1/8",
      xp: "25",
      str: 4,
      dex: 16,
      con: 11,
      int: 2,
      wis: 8,
      cha: 6,
      ac: "14 (natural armor)",
      hp: "2 (1d4)",
      speed: "10 ft., fly 40 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "",
      senses: "Darkvision 60 ft., passive Perception 9",
      languages: "—",
      traits: "Blood-drinking bat-like vermin. Myla was injured by stirges.",
      actions: "Blood Drain. Melee Weapon Attack: +5 to hit, reach 5 ft., one creature. Hit: 6 (1d4+4) piercing damage, and the stirge attaches. While attached, stirge can't attack and moves with target. Can detach with 5 ft. move.\n\nAttached: At start of stirge's turn, target loses 4 (1d4+2) HP due to blood loss.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Seagrow B1: 2 stirges in ceiling at level 2.\nObservatory D2: 6 stirges vs Mek and Minn.\nUse 2–4 for level 1 encounters."
    },
    {
      id: "sw-merrow",
      name: "Merrow",
      size: "Large",
      creatureType: "Monstrosity",
      alignment: "Chaotic evil",
      cr: "2",
      xp: "450",
      str: 18,
      dex: 10,
      con: 15,
      int: 8,
      wis: 10,
      cha: 9,
      ac: "13 (natural armor)",
      hp: "45 (6d10+12)",
      speed: "10 ft., swim 40 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "",
      senses: "Darkvision 60 ft., passive Perception 10",
      languages: "Abyssal, also speaks Common",
      traits: "Amphibious. Can breathe air and water.\n\nOptional prologue 'Voyage to Stormwreck Isle' — demands tribute for the Scaled Queen aboard the ship.",
      actions: "Multiattack: One bite attack and one claw or harpoon attack.\n\nBite. +6 to hit, reach 5 ft. Hit: 8 (1d8+4) piercing damage.\n\nClaw. +6 to hit, reach 5 ft. Hit: 7 (1d6+4) slashing damage.\n\nHarpoon. +6 to hit, range 20/60 ft. Hit: 9 (1d10+4) piercing damage.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Optional prologue encounter only — skip if not running the voyage scene."
    },
    {
      id: "sw-ghoul",
      name: "Ghoul",
      size: "Medium",
      creatureType: "Undead",
      alignment: "Chaotic evil",
      cr: "1",
      xp: "200",
      str: 13,
      dex: 15,
      con: 10,
      int: 7,
      wis: 10,
      cha: 8,
      ac: "12",
      hp: "22 (5d8)",
      speed: "30 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "Poison",
      conditionImmunities: "Charmed, exhaustion, poisoned",
      senses: "Darkvision 60 ft., passive Perception 10",
      languages: "Common",
      traits: "Cunning undead in the Compass Rose hold. Waits until party fights the zombie on lower deck, then tries to paralyze and drag a victim away.",
      actions: "Bite. +2 to hit, reach 5 ft. Hit: 9 (2d6+2) piercing damage.\n\nClaws. +4 to hit, reach 5 ft. Hit: 7 (2d4+2) slashing damage. Target must succeed DC 10 Con save or be paralyzed for 1 minute (repeat save end of turn).",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Compass Rose C8 lower deck — aft, in the water with a zombie."
    },
    {
      id: "sw-myconid",
      name: "Myconid",
      size: "Medium",
      creatureType: "Plant",
      alignment: "Lawful neutral",
      cr: "1/4",
      xp: "50",
      str: 12,
      dex: 10,
      con: 14,
      int: 10,
      wis: 13,
      cha: 7,
      ac: "13 (natural armor)",
      hp: "22 (5d8)",
      speed: "20 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "",
      senses: "Darkvision 120 ft., passive Perception 11",
      languages: "—",
      traits: "Distress Spores. When myconid takes damage, all other myconids within 240 ft. can sense its pain.\n\nRapport Spores (3/day). 30-ft. radius. Creatures with Int 2+ gain telepathy with each other for 1 hour.\n\nNot evil — start hostile but can be parleyed (DC 20 Charisma).",
      actions: "Fist. +3 to hit, reach 5 ft. Hit: 4 (1d4+2) bludgeoning damage plus 5 (2d4) poison damage.\n\nPacifying Spores (3/day). 5-ft. radius. DC 11 Con save or stunned for 1 minute (repeat save).",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "Seagrow Caves — fungus farm (B2) has sprouts + violet fungi disguised among mushrooms.\n\nMention Tarak or his offering → advantage on Charisma checks."
    },
    {
      id: "sw-spore-servant-octopus",
      name: "Spore Servant Octopus",
      size: "Medium",
      creatureType: "Plant",
      alignment: "Unaligned",
      cr: "1/4",
      xp: "50",
      str: 14,
      dex: 12,
      con: 14,
      int: 1,
      wis: 10,
      cha: 1,
      ac: "13",
      hp: "26 (4d8+8)",
      speed: "5 ft., swim 30 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "",
      senses: "Blindsight 30 ft., passive Perception 10",
      languages: "—",
      traits: "Seagrow Caves entrance (B1) — blocks Tarak's mushroom quest. Fungus-controlled octopus.",
      actions: "Tentacles. +4 to hit, reach 5 ft. Hit: 5 (1d6+2) bludgeoning damage.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "In the water at cave entrance. Combine with 2 stirges at level 2."
    },
    {
      id: "sw-violet-fungus",
      name: "Violet Fungus",
      size: "Medium",
      creatureType: "Plant",
      alignment: "Unaligned",
      cr: "1/4",
      xp: "50",
      str: 3,
      dex: 1,
      con: 10,
      int: 1,
      wis: 3,
      cha: 1,
      ac: "5",
      hp: "18 (4d8)",
      speed: "5 ft.",
      savingThrows: "",
      skills: "",
      damageImmunities: "",
      senses: "Blindsight 30 ft., passive Perception 6",
      languages: "—",
      traits: "Disguised among mushrooms in B2 fungus farm alongside myconid sprouts.",
      actions: "Multiattack: Two rotter tendril attacks.\n\nRotter. +1 to hit, reach 10 ft. Hit: 4 (1d8) necrotic damage.",
      bonusActions: "",
      reactions: "",
      legendaryActions: "",
      notes: "B2 Fungus Farm — hidden among harvestable mushrooms."
    }
  ],

  item: [
    {
      id: "sw-moonstone-key",
      name: "Moonstone Key",
      itemType: "Key",
      rarity: "Unique",
      value: "Priceless (quest item)",
      weight: "—",
      attunement: false,
      description: "A hexagonal key of pale moonstone veined with silver. Runara gives it to the party when they are ready to confront Sparkrender at the Clifftop Observatory.",
      properties: "Insert into the hexagonal indentation at the base of a marble dragon statue at D1 (observatory approach). Activates the energy bridge across the chasm to the tower ruins.",
      notes: "Quest item — Chapter 4. Without it the party cannot reach the observatory tower easily."
    },
    {
      id: "sw-heart-cap-mushrooms",
      name: "Heart Cap Mushrooms",
      itemType: "Herb / quest component",
      rarity: "Uncommon",
      value: "—",
      weight: "1 lb. (bundle)",
      attunement: false,
      description: "Rare fungi Tarak needs for his alchemical work and as a peace offering to the myconids of Seagrow Caves.",
      properties: "Found deeper in Seagrow Caves. Tarak's quest item. Presenting them (or mentioning Tarak) helps parley with myconids.",
      notes: "Blocked by spore servant octopus at cave entrance (B1). Tarak points party to Seagrow Caves in Chapter 1."
    },
    {
      id: "sw-cartographers-tools",
      name: "Cartographer's Tools",
      itemType: "Artisan's tools",
      rarity: "Common",
      value: "15 gp",
      weight: "6 lb.",
      attunement: false,
      description: "Professional mapmaking tools found in the captain's quarters of the Compass Rose.",
      properties: "Compass Rose C4 — part of treasure hoard with 50 gp, dagger, and a compass.",
      notes: "Loot in captain's quarters alongside zombies."
    },
    {
      id: "sw-captains-compass",
      name: "Captain's Compass",
      itemType: "Adventuring gear",
      rarity: "Common",
      value: "25 gp",
      weight: "—",
      attunement: false,
      description: "A fine magnetic compass from the Compass Rose captain's quarters.",
      properties: "Compass Rose C4 treasure.",
      notes: "Found with 50 gp, cartographer's tools, and a dagger."
    },
    {
      id: "sw-cursed-captains-chest",
      name: "Cursed Captain's Chest",
      itemType: "Cursed object",
      rarity: "Unique",
      value: "—",
      weight: "—",
      attunement: false,
      description: "The fallen captain's chest in the Compass Rose hold (C9). It crashed through the decks and anchors the curse that animates drowned sailors on the island's beaches.",
      properties: "Breaking or dispelling the curse in C8–C9 stops new zombies from rising on the beach. See booklet treasure tables for hold contents.",
      notes: "Chapter 3 finale objective. Source of zombie resurgence if ignored."
    },
    {
      id: "sw-poisoned-dart-trap",
      name: "Poisoned Dart (Crew Quarters Trap)",
      itemType: "Trap",
      rarity: "Common",
      value: "—",
      weight: "—",
      attunement: false,
      description: "A hidden floorboard trap in Compass Rose crew quarters (C6) — portrait of 'Aleitha and Brastos — together forever.'",
      properties: "+5 to hit. Hit: 1 piercing damage + 1d6 poison damage. Target must succeed DC 11 Constitution save or take poison damage.",
      notes: "200 gp hidden beneath the trapped floorboard."
    },
    {
      id: "sw-sparkrender-hoard",
      name: "Sparkrender's Treasure Hoard",
      itemType: "Treasure",
      rarity: "Varies",
      value: "See booklet",
      weight: "—",
      attunement: false,
      description: "Coins and jewels piled in the observatory tower where Sparkrender sleeps amid lightning arcing around his horns (D5–D6).",
      properties: "Reward for defeating or negotiating with Sparkrender. Use booklet treasure guidance for level-appropriate payout.",
      notes: "Finale loot. Aidron may ally if freed before or during the fight."
    },
    {
      id: "sw-mylas-equipment",
      name: "Myla's Equipment Stock",
      itemType: "Shop inventory",
      rarity: "Common",
      value: "PHB prices",
      weight: "—",
      attunement: false,
      description: "Myla the winged kobold sells standard adventuring equipment from the Player's Handbook at Dragon's Rest.",
      properties: "Available after meeting the cloister inhabitants. Myla also experiments with alchemy — potential source of odd consumables at DM discretion.",
      notes: "Chapter 1 — free room and board; gear available from Myla."
    }
  ],

  location: [
    {
      id: "sw-stormwreck-isle",
      name: "Stormwreck Isle",
      mapImage: "",
      description: "A small island on the Sword Coast with a foreboding name. Seaweed shimmers in brilliant colors; rays of sunlight illuminate lush grass and dark basalt rock. Calm harbor on the north side. Shaped by centuries of dragon conflict and draconic magic.",
      npcs: [],
      monsters: ["Zombie (drowned sailors on beach)", "Merrow (optional prologue only)"],
      itemsOfInterest: ["Recent shipwrecks north of cloister", "Draconic spiritual scars where dragons died"],
      featuredIn: ["Dragons of Stormwreck Isle"],
      notes: "Adventure for levels 1–3. Red dragon Sharruth imprisoned beneath the sea — her fury shaped the volcanoes here."
    },
    {
      id: "sw-dragons-rest",
      name: "Dragon's Rest",
      mapImage: "",
      description: "Cloister and home base. Open-air temple perched on a cliff edge; path from the beach dotted with doorways cut into rock. Cells, library, dining hall, and gardens. Founded by Runara a century ago as sanctuary for those seeking peace.",
      npcs: ["Elder Runara", "Tarak", "Varnoth", "Myla", "Laylee", "Rix", "Nine lawful good kobolds"],
      monsters: [],
      itemsOfInterest: ["Temple (non-evil +1d4 to saves)", "Myla's equipment shop", "Tarak's gardens"],
      featuredIn: ["Dragons of Stormwreck Isle — Chapter 1"],
      notes: "All adventure sites are a few miles away. Party gets free room and board. Protection aura in temple."
    },
    {
      id: "sw-beach-harbor",
      name: "Beach & Harbor (Dragon's Rest)",
      mapImage: "",
      description: "Calm harbor on the island's north side where the party's ship drops anchor. Long path winds up the cliff to the cloister. Site of the drowned sailors encounter.",
      npcs: [],
      monsters: ["Zombie ×3 (drowned sailors)"],
      itemsOfInterest: ["Path to cloister", "Recent shipwreck debris"],
      featuredIn: ["Dragons of Stormwreck Isle — Chapter 1"],
      notes: "Three zombies from recent shipwreck — fight optional (they can't catch party up the path). Undead Fortitude applies."
    },
    {
      id: "sw-seagrow-caves",
      name: "Seagrow Caves",
      mapImage: "",
      description: "Sea caves at the base of a two-hundred-foot cliff of dark gray stone. A swirling slick of colors dances on the water's surface, emanating from the cave. Home to myconids; linked to Sharruth's grave and the Elemental Plane of Fire.",
      npcs: ["Sinensa (myconid leader, ill)"],
      monsters: ["Myconid", "Myconid sprouts", "Spore servant octopus (B1)", "Stirge ×2 (B1, level 2+)", "Violet fungus (B2)"],
      itemsOfInterest: ["B1 Entrance — octopus in water", "B2 Fungus Farm — sprouts & violet fungi", "B6 Crystal Cave — fire-plane link, sulfur smell", "Heart cap mushrooms (Tarak's quest)"],
      featuredIn: ["Dragons of Stormwreck Isle — Chapter 2"],
      notes: "Reach by rowboat (5 mi, ~3 hr 20 min) or coastal walk (7 mi, ~2 hr 20 min).\n\nTides: Low midnight–sunrise & noon–sunset; High sunrise–noon & sunset–midnight.\n\nDC 20 Charisma to parley with myconids; Tarak mention = advantage."
    },
    {
      id: "sw-compass-rose",
      name: "Compass Rose (Shipwreck)",
      mapImage: "",
      description: "Older shipwreck north of the cloister — source of the zombies plaguing the beach. Several ships have crashed here; the latest veered off course suddenly (witnessed by Varnoth and Rix). Cursed cargo in the hold animates drowned sailors.",
      npcs: [],
      monsters: ["Zombie ×2 (C4 captain's quarters)", "Zombie + Ghoul (C8 lower deck)"],
      itemsOfInterest: ["C3 Wheel — 'Compass Rose' engraved; noise attracts C4 zombies", "C4 Captain's Quarters — 50 gp, tools, compass, dagger", "C6 Crew Quarters — trapped floorboard, 200 gp, lovers' portrait", "C8 Lower Deck — ghoul ambush", "C9 Hold — captain's chest, curse heart"],
      featuredIn: ["Dragons of Stormwreck Isle — Chapter 3"],
      notes: "Breaking the hold curse stops new beach zombies. Can be done before or after Seagrow Caves (party choice)."
    },
    {
      id: "sw-clifftop-observatory",
      name: "Clifftop Observatory",
      mapImage: "",
      description: "Ruined observatory where Runara killed a blue dragon a century ago. Sparkrender has claimed it for a ritual when the King-Killer Star comet is nearest. Marble dragon statues veined with gold; energy bridge to tower; star map floor in gold and gems.",
      npcs: ["Mek", "Minn", "Aidron (prisoner)"],
      monsters: ["Sparkrender", "Stirge ×6 (D2 rotunda)", "Sparkrender's kobold minions"],
      itemsOfInterest: ["D1 — moonstone key slot in dragon statue", "D2 Rotunda — golden sculpture (DC 15 Arcana: comet approaching)", "Dragon effigies: Astalagan, Clyssavar, Eldenemir, Sharruth, Turadaer", "D5–D6 Tower — Sparkrender's hoard, finale"],
      featuredIn: ["Dragons of Stormwreck Isle — Chapter 4"],
      notes: "Requires moonstone key from Runara. Party should complete Ch 2 and Ch 3 first.\n\nHelp Mek & Minn vs stirges → friendly kobolds may fetch key.\n\nFinale: fight, negotiate, or creative solutions with Sparkrender."
    }
  ]
};
